Work around odd cwltool issue with DockerGpuRequirement
Two workflow steps which reference the same CWL CommandLineTool apparently
cause one of the DockerGpuRequirements to be replaced by
'file:///path/to/step/parent/dir/DockerGpuRequirement', resulting in:

"""
INFO /hive/users/ruffalo/.opt/anaconda3/bin/cwltool 2.0.20200225153243
INFO Resolved '/hive/users/ruffalo/workspace/codex-pipeline/pipeline.cwl' to 'file:///hive/users/ruffalo/workspace/codex-pipeline/pipeline.cwl'
../workspace/codex-pipeline/steps/cytokit.cwl:7:3: checking item
                                                     Field `class` contains undefined reference to
                                                     `file:///hive/users/ruffalo/workspace/codex-pipeline/steps/DockerGpuRequirement`
INFO ../workspace/codex-pipeline/steps/cytokit.cwl:7:3: Unknown hint
                                                   file:///hive/users/ruffalo/workspace/codex-pipeline/steps/DockerGpuRequirement
INFO [workflow ] start
"""

I suspect I didn't add the DockerGpuRequirement to enough schemas/locations
or something like that -- but while figuring that out, work around this.